#!/bin/sh

set -e

if [ "$1" = purge ]; then
    ucf --purge /etc/beldex/belnet.ini
    ucfr --purge belnet /etc/beldex/belnet.ini
    rm -f /etc/beldex/belnet.ini
    rm -rf /var/lib/belnet/{*.{signed,private},belnet.pid,metrics.json,profiles.dat,netdb}
fi

# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'belnet-testnet.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'belnet-testnet.service' >/dev/null || true
		deb-systemd-helper unmask 'belnet-testnet.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'belnet.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'belnet.service' >/dev/null || true
		deb-systemd-helper unmask 'belnet.service' >/dev/null || true
	fi
fi
# End automatically added section


